export default {
  index: 'Introduction',
  'getting-started': 'App quickstart',
  studio: 'Lizard Studio',
  'framework-guides': 'Framework guides',
  guides: 'Guides',
  platform: 'Limits & operations',
  concepts: 'Core Concepts',
  deploy: 'Deploying',
  variables: 'Variables',
  networking: 'Networking',
  addons: 'Managed Addons',
  sandboxes: 'Sandboxes',
  observability: 'Observability',
  cli: 'CLI Reference',
  dashboard: 'App dashboard',
  agents: 'Coding agents',
};
