export default {
  index: 'Overview',
  json: 'JSON & Automation',
  '-- auth': { type: 'separator', title: 'Auth & account' },
  login: 'login',
  logout: 'logout',
  whoami: 'whoami',
  workspace: 'workspace',
  '-- projects': { type: 'separator', title: 'Projects & linking' },
  init: 'init',
  link: 'link',
  unlink: 'unlink',
  status: 'status',
  project: 'project',
  config: 'config',
  '-- create': { type: 'separator', title: 'Creating services & addons' },
  add: 'add',
  '-- deploy': { type: 'separator', title: 'Deploying' },
  up: 'up',
  redeploy: 'redeploy',
  restart: 'restart',
  '-- svc': { type: 'separator', title: 'Service configuration' },
  service: 'service',
  port: 'port',
  scale: 'scale',
  '-- secrets': { type: 'separator', title: 'Secrets' },
  secrets: 'secrets',
  '-- domains': { type: 'separator', title: 'Domains' },
  domain: 'domain',
  '-- observability': { type: 'separator', title: 'Logs, metrics & events' },
  logs: 'logs',
  metrics: 'metrics',
  events: 'events',
  ps: 'ps',
  '-- running': { type: 'separator', title: 'Running commands' },
  run: 'run',
  ssh: 'ssh',
  '-- github': { type: 'separator', title: 'GitHub' },
  git: 'git',
  '-- misc': { type: 'separator', title: 'Misc' },
  regions: 'regions',
  open: 'open',
  docs: 'docs',
  upgrade: 'upgrade',
  skills: 'skills',
};
